### PR TITLE
Use master branch of ansible-role-hardening-2

### PR DESCRIPTION
**Pull request by bra1ncramp**
## 🗣 Description ##

Use master branch of ansible-role-hardening-2

## 💭 Motivation and context ##

Currently, we are using https://github.com/cisagov/ansible-role-hardening-2/tree/cisagov-changes to harden our Ubuntu server.

After the cisagov-changes branch has been merged into the default branch, we should revert the change in 81f01a4 so that we point to the default branch.

Additionally, the TODO comment added in 4feb302 should also be removed.

See https://github.com/cisagov/ubuntu-server-packer/issues/16

## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [X] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [X] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [x] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
🎉

**Comment by dav3r** [comment]
@bra1ncramp This PR still needs a version bump before we can merge it.  Also, have you tested this by creating a Staging AMI and validating it?

**Comment by bra1ncramp** [comment]
> @bra1ncramp This PR still needs a version bump before we can merge it.  Also, have you tested this by creating a Staging AMI and validating it?

I'll work on that tomorrow

**Comment by bra1ncramp** [comment]
Successfully built AMI and passed Nessus scans.

**Pull request merged**
